### ISSUE TITLE
1900 Chinese Empire Unplayable

### ISSUE THREAD

**Issue by SinoSteel** [stuffi3000/Rise-of-Nations#98]
I don't know what you guys were thinking but the entire set up is completely wrong and unplayable. You start off with 62,000 men in the field? What? Upwards of 300,000 Imperial Army troops fought in the Boxer Rebellion against foreign powers. By May 20thish you are able to train another 3 divisions making it 68,000 men in total? Qing China not Chinese Empire or even Qing Empire should be starting off with no airforce debuffs cutting into all these others things which for whatever reason you all set to medium. Airbases should be removed from the entire game's map at 1900. Your modifiers for policies makes no sense. The focuses are wrong. The timeline of the Eight Nation Alliance is wrong. Relief expeditions is wrong. Invasion by Imperial Russia doesn't occur until June, your focuses start at Jan 1. There was no formal declaration of war. This was imperialist interventionism. There's no point in putting a Boxer support focus tree if you are going to half ass it and make it absolutely impossible and pointless. Since you choose to make this a war declaring kind of event play. The seas are automatically controlled by Japan. You can't make military access agreements with any of the breakaway provinces and retaking territory justification is too long to say of nothing if you attack one, the other ones will be dragged in so you have literally everywhere caving in the moment war is declared so you can't attack Weihaiwei Qingdao, Guangzhouwan, or Hong Kong. The modifiers for almost everything doesn't even make sense. I had great hopes when I tried the mod but it was dashed by all this nonsense. Even the suppress the Boxers focus line is just meaningless. If you are going to put in a description in saying most of the Imperial Army was still using swords, spears, and wooden boats against modern arms, cannons, and ironclads... then at least put in new infantry equipment reflecting that. Even End of a New Beginning got that right. By 1900 most of the Imperial Army isn't even armed with swords, spears, and wooden boats (Imperial Navy) so that's just laziness and bigotry on your end. Unfortunately, that mod got drama and is fracturing as well as being scaled back. Agrarian whatever should not give a 20 or was it 25% consumer goods... everyone's a fucking farmer or less than 10% of China's population is producing such goods. If you are trying to reflect that, do it properly. -20% consumer goods than put in another modifier for Industrialization as more people stop being farmers and workers in factories, consumer goods % increases or decrease. Yet again another thing EoaNB gets right. Outdated Army should not be giving you -30%? was it modifier to research speed. Makes absolutely no sense. I'm going to try the 2000 start date and if this mod is still so distasteful. I'm not playing it anymore.

**Comment by antmrt** [comment]
Guess what? We didn't fully finish adding everything yet, of you don't want to play it, then don't play it. It is clearly said that everything is WIP, but I guess you only want to complain and shit on us

**Comment by antmrt** [comment]
Thank you for your feedback, but there was no need to be so salty

**Comment by AndyYu25** [comment]
Hi, 
First, I would note that the Qing are still very much in development. We're currently working on fixing and overhauling the focus tree and certain events. 
`Upwards of 300,000 Imperial Army troops fought in the Boxer Rebellion against foreign powers.`
Wikipedia and the Cambridge History of China state around 100k Imperial soldiers. We will update the order of battle to fix that, but we're not going to have 300k soldiers for the Qing. 
`Invasion by Imperial Russia doesn't occur until June, your focuses start at Jan 1. `
It takes several focuses before the Qing declares war on the Europeans, and we're working on adjusting the lengths of those focuses so that the Qing declare in June.
`There's no point in putting a Boxer support focus tree if you are going to half ass it and make it absolutely impossible and pointless`
As said earlier, the focus tree is still under development.
`The seas are automatically controlled by Japan.`
The Imperial Chinese Navy historically had no ability to contest the seas in 1900 given the losses suffered in the 1st Sino-Japanese War, so I think that's accurate.
`You can't make military access agreements with any of the breakaway provinces and retaking territory justification is too long to say of nothing if you attack one, the other ones will be dragged in so you have literally everywhere caving in the moment war is declared so you can't attack Weihaiwei Qingdao, Guangzhouwan, or Hong Kong.`
The Mutual Defense Pact of the Southeastern Provinces is historically accurate.

**Comment by SinoSteel** [comment]
> Guess what? We didn't fully finish adding everything yet, of you don't want to play it, then don't play it. It is clearly said that everything is WIP, but I guess you only want to complain and shit on us

Not really to shit on you guys. It's just appalling and my disappointment is evident

It's different from other mods and not in a good way in some aspects

**Comment by stuffi3000** [comment]
@SinoSteel

The whole idea of WIP means that it's in development and not finished yet.

If you don't like it, give us some constructive criticism or don't play it. If you can't manage the neutrally write down your "disappointment", your "issue" has nothing to do here.

Since this won't lead anywhere anyways: locked and closed.
